# Generated by Django 4.1.1 on 2022-09-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
            preserve_default=False,
        ),
    ]
