# Generated by Django 4.1.1 on 2022-09-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
        ),
    ]
