# Generated by Django 4.1.1 on 2022-09-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_tag_note_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
