# Generated by Django 4.1.1 on 2022-09-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
